### PR TITLE
Tapered guide component

### PR DESCRIPTION
**Pull request by ckendrick**
This adds a Numba implementation of the tapered guide component.

### CODE REVIEW

**Comment by yxqd** [comment]
@ckendrick should we merge this?

**Comment by ckendrick** [comment]
@yxqd I will push a few minor changes and then it should be ready to merge. I'll open another PR for the optimized versions.

**Comment by yxqd** [comment]
@ckendrick is this OK to merge?

**Comment by ckendrick** [comment]
@yxqd This should be ok to merge now when CI passes.

**Comment by yxqd** [comment]
Thanks, @ckendrick !

**Pull request merged**
